config/routes.rb
Rails.application.routes.draw do
  resources :publications
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: redirect('/publications')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/publication.rb
class Publication < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]

  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
      params.require(:publication).permit(:title, :description, :image_url, :sound_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | BirdsSounds
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

    link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'
  body
    .container.pb-3
      .row
        .col
          = yield

app/views/publications/_form.html.slim
= simple_form_for publication,
                  defaults: { required: true,
                              wrapper_html: { class: 'row' },
                              label_html: { class: 'col-sm-auto col-form-label'},
                              input_html: { class: 'col-sm' } } do |f|
  = f.input :title
  = f.input :description
  = f.input :image_url
  = f.input :sound_url
  = f.button :submit, class: 'btn-light'

app/views/publications/edit.html.slim
h1
  | Editing Publication
= render 'form', publication: @publication
= link_to 'Show', @publication
|  | 
= link_to 'Back', publications_path

app/views/publications/index.html.slim
p#notice = notice

span.navbar-brand = 'Index'
= link_to 'New Publication', new_publication_path, class: 'btn btn-light'
- @publications.each do |publication|
  hr
  .d-flex
    .d-none.d-sm-block.mt-2
      a href=publication.image_url
        img.rounded src=publication.image_url
    .flex-grow-1.ml-4.mr-5
      a href=publication.image_url
        h5.text-dark = publication.title
        .text-sm.mb-2 = "Published on #{publication.created_at}"
      .text-muted.text-sm = publication.description
      br
      audio src=publication.sound_url controls='true'

app/views/publications/new.html.slim
p#notice = notice

span.navbar-brand = 'New Publication'
= link_to 'Back', publications_path, class: 'btn btn-light'
hr
= render 'form', publication: @publication

app/views/publications/show.html.slim
p#notice
  = notice
p
  strong
    | Title:
  = @publication.title
p
  strong
    | Description:
  = @publication.description
p
  strong
    | Image url:
  = @publication.image_url
p
  strong
    | Sound url:
  = @publication.sound_url
= link_to 'Edit', edit_publication_path(@publication)
|  | 
= link_to 'Back', publications_path